// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: lsm/lsm.proto

package lsm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_lsm_lsm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{0}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_lsm_lsm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{1}
}

func (x *SetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_lsm_lsm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_lsm_lsm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_lsm_lsm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_lsm_lsm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListPushRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ListPushRequest) Reset() {
	*x = ListPushRequest{}
	mi := &file_lsm_lsm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPushRequest) ProtoMessage() {}

func (x *ListPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPushRequest.ProtoReflect.Descriptor instead.
func (*ListPushRequest) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{6}
}

func (x *ListPushRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ListPushRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ListPushResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ListPushResponse) Reset() {
	*x = ListPushResponse{}
	mi := &file_lsm_lsm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPushResponse) ProtoMessage() {}

func (x *ListPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPushResponse.ProtoReflect.Descriptor instead.
func (*ListPushResponse) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{7}
}

func (x *ListPushResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListPopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *ListPopRequest) Reset() {
	*x = ListPopRequest{}
	mi := &file_lsm_lsm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopRequest) ProtoMessage() {}

func (x *ListPopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopRequest.ProtoReflect.Descriptor instead.
func (*ListPopRequest) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{8}
}

func (x *ListPopRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListPopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value   string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ListPopResponse) Reset() {
	*x = ListPopResponse{}
	mi := &file_lsm_lsm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPopResponse) ProtoMessage() {}

func (x *ListPopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPopResponse.ProtoReflect.Descriptor instead.
func (*ListPopResponse) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{9}
}

func (x *ListPopResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ListPopResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetAddRequest) Reset() {
	*x = SetAddRequest{}
	mi := &file_lsm_lsm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAddRequest) ProtoMessage() {}

func (x *SetAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAddRequest.ProtoReflect.Descriptor instead.
func (*SetAddRequest) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{10}
}

func (x *SetAddRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetAddRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SetAddResponse) Reset() {
	*x = SetAddResponse{}
	mi := &file_lsm_lsm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAddResponse) ProtoMessage() {}

func (x *SetAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAddResponse.ProtoReflect.Descriptor instead.
func (*SetAddResponse) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{11}
}

func (x *SetAddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetRemoveRequest) Reset() {
	*x = SetRemoveRequest{}
	mi := &file_lsm_lsm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemoveRequest) ProtoMessage() {}

func (x *SetRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemoveRequest.ProtoReflect.Descriptor instead.
func (*SetRemoveRequest) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{12}
}

func (x *SetRemoveRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRemoveRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SetRemoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SetRemoveResponse) Reset() {
	*x = SetRemoveResponse{}
	mi := &file_lsm_lsm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRemoveResponse) ProtoMessage() {}

func (x *SetRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRemoveResponse.ProtoReflect.Descriptor instead.
func (*SetRemoveResponse) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{13}
}

func (x *SetRemoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SortedSetAddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Score int32  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *SortedSetAddRequest) Reset() {
	*x = SortedSetAddRequest{}
	mi := &file_lsm_lsm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortedSetAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortedSetAddRequest) ProtoMessage() {}

func (x *SortedSetAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortedSetAddRequest.ProtoReflect.Descriptor instead.
func (*SortedSetAddRequest) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{14}
}

func (x *SortedSetAddRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SortedSetAddRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SortedSetAddRequest) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SortedSetAddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SortedSetAddResponse) Reset() {
	*x = SortedSetAddResponse{}
	mi := &file_lsm_lsm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortedSetAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortedSetAddResponse) ProtoMessage() {}

func (x *SortedSetAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortedSetAddResponse.ProtoReflect.Descriptor instead.
func (*SortedSetAddResponse) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{15}
}

func (x *SortedSetAddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SortedSetRemoveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SortedSetRemoveRequest) Reset() {
	*x = SortedSetRemoveRequest{}
	mi := &file_lsm_lsm_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortedSetRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortedSetRemoveRequest) ProtoMessage() {}

func (x *SortedSetRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortedSetRemoveRequest.ProtoReflect.Descriptor instead.
func (*SortedSetRemoveRequest) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{16}
}

func (x *SortedSetRemoveRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SortedSetRemoveRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SortedSetRemoveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *SortedSetRemoveResponse) Reset() {
	*x = SortedSetRemoveResponse{}
	mi := &file_lsm_lsm_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortedSetRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortedSetRemoveResponse) ProtoMessage() {}

func (x *SortedSetRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortedSetRemoveResponse.ProtoReflect.Descriptor instead.
func (*SortedSetRemoveResponse) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{17}
}

func (x *SortedSetRemoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HashSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field string `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HashSetRequest) Reset() {
	*x = HashSetRequest{}
	mi := &file_lsm_lsm_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashSetRequest) ProtoMessage() {}

func (x *HashSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashSetRequest.ProtoReflect.Descriptor instead.
func (*HashSetRequest) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{18}
}

func (x *HashSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HashSetRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *HashSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HashSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *HashSetResponse) Reset() {
	*x = HashSetResponse{}
	mi := &file_lsm_lsm_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashSetResponse) ProtoMessage() {}

func (x *HashSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashSetResponse.ProtoReflect.Descriptor instead.
func (*HashSetResponse) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{19}
}

func (x *HashSetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type HashGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Field string `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
}

func (x *HashGetRequest) Reset() {
	*x = HashGetRequest{}
	mi := &file_lsm_lsm_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashGetRequest) ProtoMessage() {}

func (x *HashGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashGetRequest.ProtoReflect.Descriptor instead.
func (*HashGetRequest) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{20}
}

func (x *HashGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HashGetRequest) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

type HashGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *HashGetResponse) Reset() {
	*x = HashGetResponse{}
	mi := &file_lsm_lsm_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashGetResponse) ProtoMessage() {}

func (x *HashGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lsm_lsm_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashGetResponse.ProtoReflect.Descriptor instead.
func (*HashGetResponse) Descriptor() ([]byte, []int) {
	return file_lsm_lsm_proto_rawDescGZIP(), []int{21}
}

func (x *HashGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_lsm_lsm_proto protoreflect.FileDescriptor

var file_lsm_lsm_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6c, 0x73, 0x6d, 0x2f, 0x6c, 0x73, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6c, 0x73, 0x6d, 0x22, 0x34, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x53, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x22, 0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x22, 0x23, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x2a, 0x0a, 0x0e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x39, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x50,
	0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x2c, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x22, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x22, 0x41, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x37, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x2a, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x3a, 0x0a, 0x10,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2d, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x53, 0x0a, 0x13, 0x53, 0x6f, 0x72, 0x74, 0x65,
	0x64, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x30, 0x0a, 0x14,
	0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x40,
	0x0a, 0x16, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x33, 0x0a, 0x17, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x4e, 0x0a, 0x0e, 0x48, 0x61, 0x73, 0x68, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x2b, 0x0a, 0x0f, 0x48, 0x61, 0x73, 0x68, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0x38, 0x0a, 0x0e, 0x48, 0x61, 0x73, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x27, 0x0a, 0x0f,
	0x48, 0x61, 0x73, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xee, 0x04, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x6c, 0x73, 0x6d, 0x2e,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x73, 0x6d,
	0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x03,
	0x53, 0x65, 0x74, 0x12, 0x0f, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x12, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x08, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x75, 0x73, 0x68, 0x12, 0x14, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6c, 0x73,
	0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x75, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70, 0x12, 0x13, 0x2e,
	0x6c, 0x73, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6f, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x53, 0x65, 0x74, 0x41,
	0x64, 0x64, 0x12, 0x12, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x65, 0x74,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x09, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12, 0x15, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53,
	0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x16, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0c, 0x53, 0x6f, 0x72, 0x74, 0x65,
	0x64, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x12, 0x18, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x6f,
	0x72, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x53, 0x65,
	0x74, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0f,
	0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x12,
	0x1b, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x6c,
	0x73, 0x6d, 0x2e, 0x53, 0x6f, 0x72, 0x74, 0x65, 0x64, 0x53, 0x65, 0x74, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x48, 0x61,
	0x73, 0x68, 0x53, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x48, 0x61, 0x73, 0x68,
	0x53, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6c, 0x73, 0x6d,
	0x2e, 0x48, 0x61, 0x73, 0x68, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x34, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x68, 0x47, 0x65, 0x74, 0x12, 0x13, 0x2e, 0x6c, 0x73,
	0x6d, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x6c, 0x73, 0x6d, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1c, 0x5a, 0x1a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72, 0x6b, 0x6d, 0x6e, 0x67, 0x6b, 0x72, 0x2f, 0x6c, 0x73, 0x6d,
	0x2f, 0x6c, 0x73, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_lsm_lsm_proto_rawDescOnce sync.Once
	file_lsm_lsm_proto_rawDescData = file_lsm_lsm_proto_rawDesc
)

func file_lsm_lsm_proto_rawDescGZIP() []byte {
	file_lsm_lsm_proto_rawDescOnce.Do(func() {
		file_lsm_lsm_proto_rawDescData = protoimpl.X.CompressGZIP(file_lsm_lsm_proto_rawDescData)
	})
	return file_lsm_lsm_proto_rawDescData
}

var file_lsm_lsm_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_lsm_lsm_proto_goTypes = []any{
	(*SetRequest)(nil),              // 0: lsm.SetRequest
	(*SetResponse)(nil),             // 1: lsm.SetResponse
	(*GetRequest)(nil),              // 2: lsm.GetRequest
	(*GetResponse)(nil),             // 3: lsm.GetResponse
	(*DeleteRequest)(nil),           // 4: lsm.DeleteRequest
	(*DeleteResponse)(nil),          // 5: lsm.DeleteResponse
	(*ListPushRequest)(nil),         // 6: lsm.ListPushRequest
	(*ListPushResponse)(nil),        // 7: lsm.ListPushResponse
	(*ListPopRequest)(nil),          // 8: lsm.ListPopRequest
	(*ListPopResponse)(nil),         // 9: lsm.ListPopResponse
	(*SetAddRequest)(nil),           // 10: lsm.SetAddRequest
	(*SetAddResponse)(nil),          // 11: lsm.SetAddResponse
	(*SetRemoveRequest)(nil),        // 12: lsm.SetRemoveRequest
	(*SetRemoveResponse)(nil),       // 13: lsm.SetRemoveResponse
	(*SortedSetAddRequest)(nil),     // 14: lsm.SortedSetAddRequest
	(*SortedSetAddResponse)(nil),    // 15: lsm.SortedSetAddResponse
	(*SortedSetRemoveRequest)(nil),  // 16: lsm.SortedSetRemoveRequest
	(*SortedSetRemoveResponse)(nil), // 17: lsm.SortedSetRemoveResponse
	(*HashSetRequest)(nil),          // 18: lsm.HashSetRequest
	(*HashSetResponse)(nil),         // 19: lsm.HashSetResponse
	(*HashGetRequest)(nil),          // 20: lsm.HashGetRequest
	(*HashGetResponse)(nil),         // 21: lsm.HashGetResponse
}
var file_lsm_lsm_proto_depIdxs = []int32{
	2,  // 0: lsm.Database.Get:input_type -> lsm.GetRequest
	0,  // 1: lsm.Database.Set:input_type -> lsm.SetRequest
	4,  // 2: lsm.Database.Delete:input_type -> lsm.DeleteRequest
	6,  // 3: lsm.Database.ListPush:input_type -> lsm.ListPushRequest
	8,  // 4: lsm.Database.ListPop:input_type -> lsm.ListPopRequest
	10, // 5: lsm.Database.SetAdd:input_type -> lsm.SetAddRequest
	12, // 6: lsm.Database.SetRemove:input_type -> lsm.SetRemoveRequest
	14, // 7: lsm.Database.SortedSetAdd:input_type -> lsm.SortedSetAddRequest
	16, // 8: lsm.Database.SortedSetRemove:input_type -> lsm.SortedSetRemoveRequest
	18, // 9: lsm.Database.HashSet:input_type -> lsm.HashSetRequest
	20, // 10: lsm.Database.HashGet:input_type -> lsm.HashGetRequest
	3,  // 11: lsm.Database.Get:output_type -> lsm.GetResponse
	1,  // 12: lsm.Database.Set:output_type -> lsm.SetResponse
	5,  // 13: lsm.Database.Delete:output_type -> lsm.DeleteResponse
	7,  // 14: lsm.Database.ListPush:output_type -> lsm.ListPushResponse
	9,  // 15: lsm.Database.ListPop:output_type -> lsm.ListPopResponse
	11, // 16: lsm.Database.SetAdd:output_type -> lsm.SetAddResponse
	13, // 17: lsm.Database.SetRemove:output_type -> lsm.SetRemoveResponse
	15, // 18: lsm.Database.SortedSetAdd:output_type -> lsm.SortedSetAddResponse
	17, // 19: lsm.Database.SortedSetRemove:output_type -> lsm.SortedSetRemoveResponse
	19, // 20: lsm.Database.HashSet:output_type -> lsm.HashSetResponse
	21, // 21: lsm.Database.HashGet:output_type -> lsm.HashGetResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_lsm_lsm_proto_init() }
func file_lsm_lsm_proto_init() {
	if File_lsm_lsm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_lsm_lsm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lsm_lsm_proto_goTypes,
		DependencyIndexes: file_lsm_lsm_proto_depIdxs,
		MessageInfos:      file_lsm_lsm_proto_msgTypes,
	}.Build()
	File_lsm_lsm_proto = out.File
	file_lsm_lsm_proto_rawDesc = nil
	file_lsm_lsm_proto_goTypes = nil
	file_lsm_lsm_proto_depIdxs = nil
}
